"""
Modulo com informações constantes
"""


str_to_num={'primeira':1,'segunda':2,'terceira':3,'quarta':4,'quinta':5,'sexta':6,'setima':7,'oitava':8,'nona':9,'decima':10,'primeiro':1,'segundo':2,'terceiro':3,'quarto':4,'quinto':5,'sexto':6,'setimo':7,'oitavo':8,'nono':9,'decimo':10}


areas = {'administração':0,'administração pública':0,'administração de empresas':0,'contábeis':0,
		'ciências contábeis':0,'turismo':0,'antropologia':1,'arqueologia':1,'arquitetura':2,'urbanismo':2,'design':3,
		'artes':3,'astronomia':4,'física':4,'biodiversidade':5,'biotecnologia':6,'ciência da computação':7,'computação':7,
		'ciência de alimentos':8,'alimentos':8,'ciência política':9,'política':9,'relações internacionais':9,'relações':9,
		'ciências agrárias 1':10,'ciências ambientais':11,'ambientais':11,'biológicas 1':12,'biológicas 2':13,
		'biológicas 3':14,'ciências biológicas 1':12,'ciências biológicas 2':13,'ciências biológicas 3':14,
		'ciências da religião e teologia':15,'religião':15,'teologia':15,'comunicação e informação':16,'comunicação':16,
		'informação':16,'direito':17,'economia':18,'educação':19,'educação física':20,'enfermagem':21,'engenharias 1':22,
		'engenharias 2':23,'engenharias 3':24,'engenharias iv':25,'ensino':26,'farmácia':27,'filosofia':28,'geociências':29,
		'geografia':30,'história':31,'interdisciplinar':32,'linguística':33,'literatura':33,'linguística e literatura':33,
		'matemática':34,'probabilidade':34,'estatística':34,'materiais':35,'medicina 1':36,'medicina 2':37,'medicina 3':38,
		'medicina veterinária':39,'nutrição':40,'odontologia':41,'odonto':41,'dentistaria':41,'planejamento':42,
		'planejamento urbano':42,'planejamento regional':42,'demografia':42,'psicologia':43,'química':44,'saúde coletiva':45,
		'serviço social':46,'sociologia':47,'zootecnia':48,'recursos pesqueiros':48}
    
vocab=['administração','administração pública','administração de empresas','contábeis',
		'ciências contábeis','turismo','antropologia','arqueologia','arquitetura','urbanismo','design',
		'artes','astronomia','física','biodiversidade','biotecnologia','ciência da computação','computação',
		'ciência de alimentos','alimentos','ciência política','política','relações internacionais','relações',
		'ciências agrárias 1','ciências ambientais','ambientais','biológicas 1','biológicas 2',
		'biológicas 3','ciências biológicas 1','ciências biológicas 2','ciências biológicas 3',
		'ciências da religião e teologia','religião','teologia','comunicação e informação','comunicação',
		'informação','direito','economia','educação','educação física','enfermagem','engenharias 1',
		'engenharias 2','engenharias 3','engenharias 4','ensino','farmácia','filosofia','geociências',
		'geografia','história','interdisciplinar','linguística','literatura','linguística e literatura',
		'matemática','probabilidade','estatística','materiais','medicina 1','medicina 2','medicina 3',
		'medicina veterinária','nutrição','odontologia','odonto','dentistaria','planejamento',
		'planejamento urbano','planejamento regional','demografia','psicologia','química','saúde coletiva',
		'serviço social','sociologia','zootecnia','recursos pesqueiros']




AREAS = {

    "administração": 0,
    "administração pública": 0,
    "administração de empresas": 0,
    "contábeis": 0,
    "ciências contábeis": 0,
    "turismo": 0,
    "antropologia": 1,
    "arqueologia": 1,
    "arquitetura": 2,
    "urbanismo": 2,
    "design": 3,
    "artes": 3,
    "astronomia": 4,
    "física": 4,
    "biodiversidade": 5,
    "biotecnologia": 6,
    "ciência da computação": 7,
    "computação": 7,
    "ciência de alimentos": 8,
    "alimentos": 8,
    "ciência política": 9,
    "política": 9,
    "relações internacionais": 9,
    "relações": 9,
    "ciências agrárias i": 10,
    "ciências ambientais": 11,
    "ambientais": 11,
    "biológicas i": 12,
    "biológicas ii": 13,
    "biológicas iii": 14,
    "ciências biológicas i": 12,
    "ciências biológicas ii": 13,
    "ciências biológicas iii": 14,
    "ciências da religião e teologia": 15,
    "religião": 15,
    "teologia": 15,
    "comunicação e informação": 16,
    "comunicação": 16,
    "informação": 16,
    "direito": 17,
    "economia": 18,
    "educação": 19,
    "educação física": 20,
    "enfermagem": 21,
    "engenharias i": 22,
    "engenharias ii": 23,
    "engenharias iii": 24,
    "engenharias iv": 25,
    "ensino": 26,
    "farmácia": 27,
    "filosofia": 28,
    "geociências": 29,
    "geografia": 30,
    "história": 31,
    "interdisciplinar": 32,
    "linguística": 33,
    "literatura": 33,
    "linguística e literatura": 33,
    "matemática": 34,
    "probabilidade": 34,
    "estatística": 34,
    "materiais": 35,
    "medicina i": 36,
    "medicina ii": 37,
    "medicina iii": 38,
    "medicina veterinária": 39,
    "nutrição": 40,
    "odontologia": 41,
    "odonto": 41,
    "dentistaria": 41,
    "planejamento": 42,
    "planejamento urbano": 42,
    "planejamento regional": 42,
    "demografia": 42,
    "psicologia": 43,
    "química": 44,
    "saúde coletiva": 45,
    "serviço social": 46,
    "sociologia": 47,
    "zootecnia": 48,
    "recursos pesqueiros": 48,
}
